### PR TITLE
Headroom.js

### PR DESCRIPTION
**Pull request by apreshill**
thanks to @gadenbuie for the assist!!

### CODE REVIEW

**Comment by gadenbuie** [comment]
I can't tell from the logs which version of Hugo is being used, but I think we need at least [Hugo 0.74.0](https://gohugo.io/news/0.74.0-relnotes/). I tested locally with `hugodown::hugo_install('0.79.0')`.

**Comment by apreshill** [comment]
Thanks- I'll look into this, I'm using:

https://github.com/apreshill/blogophonic/blob/3c0be230238422f57f724802ac767a8a3b436517/netlify.toml#L5

**Comment by gadenbuie** [comment]
Oh I see, that commit was after you started the headroom branch so `netlify.toml` isn't in this PR branch

**Comment by apreshill** [comment]
Aha! I pulled it in and looks like I'm back in business, thanks!

**Pull request merged**
