### PR TITLE
Theme3

### PR DESCRIPTION
**Pull request by dcossyleon**
Reddish orange

### CODE REVIEW

**Comment by apreshill** [comment]
Blurg color contrast flag. Change darker to #C44C2B, then lighter "READ MORE" to #C54B29 😞

**Comment by apreshill** [comment]
ok this one was most affected sadly- let me know if you have any ideas 💡

**Comment by dcossyleon** [comment]
Hmm let me think about to re-work this one

**Comment by apreshill** [comment]
Thank you! I love this one too of course 💟

**Pull request merged**
